#docker.io
#docker-compose
#docker started

---

- hosts: python-app-server
  gather_facts: False
  become: True
  tasks:
    - name: Update apt
      apt:
        update_cache: true
        force_apt_get: true
        
    - name: Install Dockerio
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Habilitar Docker no boot
      service:
        name: docker
        enabled: yes
        state: started

    - name: Copiando arquivos para servidor
      copy:
        src: "{{ item }}"
        dest: "/home/admin/{{ item }}"
      with_items:
        - docker-compose.yml
        - Dockerfile
        - app.py
        - requirements.txt

    - name: Construindo docker
      command: docker build -t pythonapp:1.0 .
      register: docker_build

    - name: Run Docker 
      command: docker-compose up -d
      register: docker_compose_up
      


